/* eslint-disable */

export const API_BASE_URL = CONFIG.API_BASE_URL;
export const JWT_PUBLIC_KEY = atob(CONFIG.JWT_PUBLIC_KEY);
export const OAUTH2_INIT_ENDPOINT = CONFIG.OAUTH2_INIT_ENDPOINT;
export const OAUTH2_LOGIN_ENDPOINT = CONFIG.OAUTH2_LOGIN_ENDPOINT;

export default {
  API_BASE_URL,
  JWT_PUBLIC_KEY,
  OAUTH2_INIT_ENDPOINT,
  OAUTH2_LOGIN_ENDPOINT
}
