steps:
  # Back-end
  ## Run unit tests
  ## Downgrade Maven due to https://github.com/gleclaire/findbugs-maven-plugin/pull/35
  ## Use Alpine-based image to mitigate https://issues.apache.org/jira/browse/SUREFIRE-1588
  - name: maven:3.5.4-jdk-8-alpine
    entrypoint: 'mvn'
    args: ['-f', 'relinkr-api', '-B', 'verify']
  ## Copy code coverage report to project's build bucket
  - name: gcr.io/cloud-builders/gsutil
    args: ['-m', 'rsync', '-r', '-d', 'relinkr-api/target/site/jacoco', 'gs://build.craftingjava.com/$REPO_NAME/$BRANCH_NAME/test/jacoco']
  ## Copy code coverage badge to project's build bucket
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'relinkr-api/target/coverage.svg', 'gs://build.craftingjava.com/$REPO_NAME/$BRANCH_NAME/test']
  # Front-end
  ## Prepare
  - name: node:10.15.3
    entrypoint: npm
    args: ['install', '--prefix', 'relinkr-ui']
  ## Compile
  - name: node:10.15.3
    entrypoint: npm
    args: ['run', 'build', '--prefix', 'relinkr-ui']
  # Publish release
  ## Publish Back-end
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'relinkr-api/target/relinkr-api.jar', 'gs://build.craftingjava.com/$REPO_NAME/$BRANCH_NAME/release/relinkr-api-$SHORT_SHA.jar']
  ## Package Front-end
  - name: gcr.io/$PROJECT_ID/zip
    args: ['-r', 'relinkr-ui-$SHORT_SHA.zip', 'relinkr-ui', '-x', '*dist*', '-x', '*node_modules*']
  ## Publish Front-end
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'relinkr-ui-$SHORT_SHA.zip', 'gs://build.craftingjava.com/$REPO_NAME/$BRANCH_NAME/release']
